version: '2'
services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.4.0
    volumes:
      - /var/lib/docker/volumes/zigbee2mqtt:/app/data
    {{- if (.Values.USB_PORT) }}
    devices:
      - ${USB_PORT}:/dev/ttyACM0
    {{- end }}
    environment:
      TZ: ${TZ}
    restart: always